services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.30.5
    restart: always
    environment:
      DOMAIN: "https://vaultwarden.localhost" # Your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "true"
    volumes:
      - type: volume
        source: vw-data
        target: /data

  caddy:
    container_name: caddy
    image: caddy:2.8.4
    restart: always
    ports:
      - name: ACME HTTP-01 challenge
        target: 80
        published: 80
        host_ip: 127.0.0.1
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        host_ip: 127.0.0.1
        protocol: tcp
        mode: host
      - name: HTTP/3
        target: 443
        published: 443
        host_ip: 127.0.0.1
        protocol: udp
        mode: host
    environment:
      DOMAIN: "https://vaultwarden.localhost" # Your domain.
      LOG_FILE: "/data/access.log"
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: volume
        source: caddy-config
        target: /config
      - type: volume
        source: caddy-data
        target: /data

volumes:
  vw-data:
  caddy-data:
  caddy-config:
