services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.30.5
    restart: always
    environment:
      DOMAIN: "https://vaultwarden.localhost" # Your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "true"
    volumes:
      - type: volume
        source: vw-data
        target: /data

  caddy:
    container_name: caddy
    image: caddy:2.8.4
    restart: always
    ports:
      - 80:80 # Needed for the ACME HTTP-01 challenge.
      - 443:443
      - 443:443/udp # Needed for HTTP/3.
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: volume
        source: caddy-config
        target: /config
      - type: volume
        source: caddy-data
        target: /data
    environment:
      DOMAIN: "https://vaultwarden.localhost" # Your domain.
      LOG_FILE: "/data/access.log"

volumes:
  vw-data:
  caddy-data:
  caddy-config:
